on:
  push:
    branches: [setup/cloudflare-integration]
jobs: #can have multiple jobs
  deploy: #name of the job (could be anything)
    runs-on: ubuntu-latest #environment in which the job will run
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps: # defines a series of steps to be executed in the job. Each step can either use an existing GitHub Action (uses) or run a command directly (run)

        #Step 1 (Clone the project)
      - name: Checkout #name of the step (could be anything)
        uses: actions/checkout@v3 # The checkout action clones your repository so that the runner has access to your code.

        #Step 2 (Run your project's build step)
      - name: Build
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        run: npm install && npm run build


      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: g-datalabs
          directory: .next 
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}